// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kddcpfszrdcetrvvaqhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkZGNwZnN6cmRjZXRydnZhcWh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MDc4MTAsImV4cCI6MjA1ODM4MzgxMH0.Zed29poHT9RTL80LNpPwTnpjQ3khwOofSwuvH6NPL28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);